version: '3.4'

services:
  basket.api:
    image: basketapi:dev
    container_name: Basket.API
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Basket.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_basket.api$
    volumes:
      - C:\Users\77071\source\repos\MicroservicesApp2\src\Basket\Basket.API:/app
      - C:\Users\77071\source\repos\MicroservicesApp2:/src
      - C:\Users\77071\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_basket.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_basket.api$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  catalog.api:
    image: catalogapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Catalog.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_catalog.api$
    volumes:
      - C:\Users\77071\source\repos\MicroservicesApp2\src\Catalog\Catalog.API:/app
      - C:\Users\77071\source\repos\MicroservicesApp2:/src
      - C:\Users\77071\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_catalog.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_catalog.api$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
